// Generated by scripts/build_universal_protocols.py.
use super::{BuiltinProtocol, Experiment};

#[rustfmt::skip]
pub const PROTOCOLS: &[BuiltinProtocol] = &[
    BuiltinProtocol { name: "static_final", experiment: Experiment::A4, extension: "toml", contents: include_str!("../protocols/acquisition/static_final.toml"), points: 1, seconds: 111.0 },
    BuiltinProtocol { name: "static_screen", experiment: Experiment::A4, extension: "toml", contents: include_str!("../protocols/acquisition/static_screen.toml"), points: 1, seconds: 66.0 },
    BuiltinProtocol { name: "static_finalist", experiment: Experiment::A4, extension: "toml", contents: include_str!("../protocols/acquisition/static_finalist.toml"), points: 1, seconds: 66.0 },
    BuiltinProtocol { name: "static_smoke", experiment: Experiment::A4, extension: "toml", contents: include_str!("../protocols/acquisition/static_smoke.toml"), points: 1, seconds: 23.0 },
    BuiltinProtocol { name: "sine_smoke", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/sine_smoke.csv"), points: 1, seconds: 16.0 },
    BuiltinProtocol { name: "steps_smoke", experiment: Experiment::A2, extension: "toml", contents: include_str!("../protocols/acquisition/steps_smoke.toml"), points: 1, seconds: 18.25 },
    BuiltinProtocol { name: "load_smoke", experiment: Experiment::A5, extension: "toml", contents: include_str!("../protocols/acquisition/load_smoke.toml"), points: 1, seconds: 20.25 },
    BuiltinProtocol { name: "screen_response", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/screen_response.csv"), points: 7, seconds: 210.0 },
    BuiltinProtocol { name: "screen_reference", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/screen_reference.csv"), points: 2, seconds: 48.0 },
    BuiltinProtocol { name: "finalist_response", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/finalist_response.csv"), points: 4, seconds: 106.0 },
    BuiltinProtocol { name: "main_1", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/main_1.csv"), points: 24, seconds: 1090.0 },
    BuiltinProtocol { name: "main_2", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/main_2.csv"), points: 22, seconds: 624.0 },
    BuiltinProtocol { name: "main_3", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/main_3.csv"), points: 24, seconds: 624.0 },
    BuiltinProtocol { name: "main_complete", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/main_complete.csv"), points: 70, seconds: 2338.0 },
    BuiltinProtocol { name: "lower_1", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/lower_1.csv"), points: 24, seconds: 1090.0 },
    BuiltinProtocol { name: "lower_2", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/lower_2.csv"), points: 22, seconds: 624.0 },
    BuiltinProtocol { name: "lower_3", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/lower_3.csv"), points: 24, seconds: 624.0 },
    BuiltinProtocol { name: "lower_complete", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/lower_complete.csv"), points: 70, seconds: 2338.0 },
    BuiltinProtocol { name: "bright_bridge", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/bright_bridge.csv"), points: 6, seconds: 156.0 },
    BuiltinProtocol { name: "intermediate_bridge", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/intermediate_bridge.csv"), points: 8, seconds: 234.0 },
    BuiltinProtocol { name: "closing_response", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/closing_response.csv"), points: 2, seconds: 52.0 },
    BuiltinProtocol { name: "slow_extension", experiment: Experiment::A1, extension: "csv", contents: include_str!("../protocols/acquisition/slow_extension.csv"), points: 2, seconds: 470.0 },
    BuiltinProtocol { name: "latency_core", experiment: Experiment::A2, extension: "toml", contents: include_str!("../protocols/acquisition/latency_core.toml"), points: 3, seconds: 192.75 },
    BuiltinProtocol { name: "latency_cadence", experiment: Experiment::A2, extension: "toml", contents: include_str!("../protocols/acquisition/latency_cadence.toml"), points: 2, seconds: 153.5 },
    BuiltinProtocol { name: "latency_bridge", experiment: Experiment::A2, extension: "toml", contents: include_str!("../protocols/acquisition/latency_bridge.toml"), points: 2, seconds: 228.5 },
    BuiltinProtocol { name: "heldout_temporal", experiment: Experiment::A2, extension: "toml", contents: include_str!("../protocols/acquisition/heldout_temporal.toml"), points: 4, seconds: 205.0 },
    BuiltinProtocol { name: "load_recovery", experiment: Experiment::A5, extension: "toml", contents: include_str!("../protocols/acquisition/load_recovery.toml"), points: 6, seconds: 319.5 },
    BuiltinProtocol { name: "load_roi_compare", experiment: Experiment::A5, extension: "toml", contents: include_str!("../protocols/acquisition/load_roi_compare.toml"), points: 1, seconds: 17.25 },
];
