#!/usr/bin/env python3
"""Emit deterministic A3 bench protocols; no fitted cutoff is assumed."""
from pathlib import Path
import csv
import io

ROOT = Path(__file__).resolve().parents[1] / "plugins/stage-a-a3/protocols"
PROFILE = "A1-bias-v1-monitoring"
FREQUENCIES = [2, 8, 32]
LOW_FREQUENCY = 0.5
LOW_DEPTHS = [0.20, 1.0]
DEPTHS = [0.06, 0.08, 0.11, 0.15, 0.20, 0.27, 0.36, 0.48, 0.63, 0.80, 1.0, 1.3]
# Offsets from the per-sensor factory trims, not absolute register codes.
BIASES = [(10, 0), (-10, 0), (0, 5), (0, -5)]
HEADER = ["camera_profile", "label", "mean_u", "frequency_hz", "depth_a", "duration_s", "settle_s", "role", "diff_on", "diff_off"]


def point(label, mean, f, a, on=0, off=0, role="", cycles=10):
    return [PROFILE, label, mean, f, a, max(10, round(cycles / f)), max(2, round(2 / f)), role, on, off]


def reference(label, mean):
    return point(label, mean, 2, 0.63, cycles=40)


def low_depth_control(label, mean):
    return point(label, mean, 2, 0.01, role="", cycles=40)


def full_baseline():
    rows = []
    for repeat in [1, 2]:
        fluxes = [0.15, 0.30, 0.45] if repeat == 1 else [0.45, 0.30, 0.15]
        for mean in fluxes:
            tag = f"baseline_pass{repeat}_u{mean}"
            rows += [low_depth_control(tag + "_low_depth_control_start", mean), reference(tag + "_reference_start", mean)]
            frequencies = FREQUENCIES if repeat == 1 else FREQUENCIES[::-1]
            # Reverse the depth sequence on pass 2 as a drift/history check.
            depths = DEPTHS if repeat == 1 else DEPTHS[::-1]
            for f in frequencies:
                for index, a in enumerate(depths):
                    rows.append(point(f"{tag}_f{f}_a{a}", mean, f, a))
                    # Retain the existing short reference brackets.
                    if (index + 1) % 3 == 0:
                        rows.append(reference(f"{tag}_ref_after_f{f}_d{index+1}", mean))
            for a in LOW_DEPTHS if repeat == 1 else LOW_DEPTHS[::-1]:
                rows.append(point(f"{tag}_slow_check_a{a}", mean, LOW_FREQUENCY, a))
            rows.append(low_depth_control(tag + "_low_depth_control_end", mean))
    return rows


def full_bias():
    rows = []
    depths = [0.11, 0.20, 0.36, 0.63, 1.0, 1.3]
    for repeat in [1, 2]:
        biases = BIASES if repeat == 1 else BIASES[::-1]
        for on, off in biases:
            tag = f"bias_pass{repeat}_on{on}_off{off}"
            rows += [low_depth_control(tag + "_anchor_low_depth_control", 0.30), reference(tag + "_anchor_reference", 0.30)]
            rows.append(point(tag + "_bias_low_depth_control_start", .30, 2, .01, on, off, "", 40))
            for f in FREQUENCIES if repeat == 1 else FREQUENCIES[::-1]:
                for index, a in enumerate(depths if repeat == 1 else depths[::-1]):
                    rows.append(point(f"{tag}_f{f}_a{a}", .30, f, a, on, off))
                    if (index + 1) % 3 == 0:
                        rows.append(reference(f"{tag}_anchor_after_f{f}_d{index+1}", .30))
            for a in LOW_DEPTHS if repeat == 1 else LOW_DEPTHS[::-1]:
                rows.append(point(f"{tag}_slow_check_a{a}", .30, LOW_FREQUENCY, a, on, off))
            rows += [point(tag + "_bias_low_depth_control_end", .30, 2, .01, on, off, "", 40), reference(tag + "_anchor_end", .30)]
    return rows


def write(name, rows, scope):
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(HEADER)
    writer.writerows(rows)
    timed = sum(row[5] + row[6] for row in rows)
    estimated = timed + 11 * len(rows)
    comments = f"""# {scope}
# Generated by scripts/build_a3_protocols.py. Do not infer scientific validity from completion.
# Emission PD after filter/50:50 splitter; measured dark reference applied; J24 sync.
# Start with the calibrated optical log-sine drive. Keep sample/ROI/mask/PD gain/load fixed.
# Profile {PROFILE}; confirm this saved profile contains bias-v1 and filters OFF.
# diff_on/off are offsets; host readback must confirm each requested bias and restoration.
# a is commanded log excursion. Compute actual dark-corrected contrast from saved PDQ offline.
# Main ladders: 2/8/32 Hz. Sparse 0.5 Hz checks; no 0.2 Hz points.
# All frequencies are candidates; test frequency independence at each flux AND bias offline.
# low_depth_control rows use a=0.01; they are NOT constant-light backgrounds.
# mean_u is a relative operating point, not calibrated photon flux. Retain registered frame references.
# Scope: effective thresholds in this optical configuration; local contrast/drift gates still apply.
# {len(rows)} recordings; {timed} s recording+settling; about {estimated/60:.1f} min with 11 s/file.
# Excludes manual references, bias readback overhead, retries and setup. Use New ID for an independent repeat.
"""
    (ROOT / name).write_text(comments + buffer.getvalue())
    print(f"{name}: {len(rows)} recordings; {timed}s timed; approx {estimated/60:.1f} min")


def main():
    ROOT.mkdir(parents=True, exist_ok=True)
    smoke = [point("low_depth_control_start", .30, 2, .01)]
    for f in FREQUENCIES:
        for a in [.30, .90]: smoke.append(point(f"smoke_f{f}_a{a}", .30, f, a))
    for a in [.30, .90]: smoke.append(point(f"slow_check_a{a}", .30, LOW_FREQUENCY, a))
    smoke += [point("repeat_f2_a0.9", .30, 2, .90), point("low_depth_control_end", .30, 2, .01)]
    write("a3_smoke.csv", smoke, "A3 technical smoke: 2/8/32 Hz, two depths, sparse 0.5 Hz checks and repeated reference.")
    core = [low_depth_control("low_depth_control_start", .30), reference("reference_start", .30)]
    for f in FREQUENCIES:
        for a in [.4, .12, .9, .18, 1.3, .27, .6, .08]:
            row = point(f"grid_f{f}_a{a}", .30, f, a); row[5] = 20
            core.append(row)
        core.append(reference(f"reference_after_{f}", .30))
    for a in [.18, .9]: core.append(point(f"slow_check_a{a}", .30, LOW_FREQUENCY, a, cycles=20))
    core.append(low_depth_control("low_depth_control_end", .30))
    write("a3_frequency_depth_core.csv", core, "A3 one-flux core: 2/8/32 Hz, eight depths, sparse 0.5 Hz checks and references.")
    baseline, bias = full_baseline(), full_bias()
    write("a3_full_baseline.csv", baseline, "A3 full baseline: 3 fluxes x 3 main frequencies x 12 depths x 2 passes, with references and sparse 0.5 Hz checks.")
    write("a3_full_bias_map.csv", bias, "A3 bias extension: one flux, four single-polarity offset variants x 3 main frequencies x 6 depths x 2 passes and sparse 0.5 Hz checks.")
    write("a3_full_scientific.csv", baseline + bias, "A3 complete planned acquisition: full baseline followed by the bias extension.")


if __name__ == "__main__":
    main()
