#!/usr/bin/env python3
"""Generate the versioned universal campaigns and their actual owner rows."""
import argparse
import csv
import io
import json
import math
from pathlib import Path

VERSION = '20260911-v5-4h'
OVERHEAD = 11.0
FREQS = [.25, .5, 1, 2, 4, 8, 16, 32, 128, 512]
DEPTHS = [.04, .08, .12, .20, .36, .80]
CANDIDATES = [dict(diff_on=on, diff_off=off, fo=fo, hpf=0, refr=235, filters_off=True)
              for fo in [0, 55] for on, off in [(0, 0), (-15, -2), (-30, -5)]]

def scalar(value):
    return json.dumps(value, ensure_ascii=False)

def sine_row(label, f, a, cycles=12, minimum=12):
    return dict(camera_profile='', label=label, mean_u=.30, frequency_hz=f,
                depth_a=a, duration_s=math.ceil(max(minimum, cycles/f)), settle_s=max(3, 2/f), role='')

def grid(freqs, depths, prefix, cycles=12, minimum=12):
    # Interleave low/middle/high frequencies; alternate depth direction.
    order = [f for trio in zip(freqs[:len(freqs)//3], freqs[len(freqs)//3:2*(len(freqs)//3)],
                              freqs[2*(len(freqs)//3):]) for f in trio]
    order += [f for f in freqs if f not in order]
    return [sine_row(f'{prefix}_f{f}_a{a}', f, a, cycles, minimum)
            for i, f in enumerate(order) for a in (depths if i%2 == 0 else list(reversed(depths)))]

class Builder:
    def __init__(self, root):
        self.root = root
        self.catalog = []
        self.files = {}

    def save(self, path, text):
        self.files[path] = text

    def acquisition(self, name, kind, extension, text, rows, seconds):
        path = f'stage-a-universal-runner/protocols/acquisition/{name}.{extension}'
        self.save(path, f'# Generated by scripts/build_universal_protocols.py; {VERSION}.\n'+text)
        self.catalog.append(dict(name=name, experiment=kind, extension=extension,
                                 points=rows, seconds=round(seconds, 6), path=path))
        return name

    def sine(self, name, rows):
        out = io.StringIO()
        writer = csv.DictWriter(out, fieldnames=list(rows[0]), lineterminator='\n')
        writer.writeheader(); writer.writerows(rows)
        return self.acquisition(name, 'A1', 'csv', out.getvalue(), len(rows),
                                sum(r['duration_s']+r['settle_s']+OVERHEAD for r in rows))

    def steps(self, name, specs, kind='A2'):
        text = f'name = "{name}"\ntiming_reference = "drive_sync"\ntrigger_validation = "offline_review"\n'
        seconds = 0
        for i, (a, half, n, role) in enumerate(specs):
            settle = 5 if kind == 'A5' else 3
            values = dict(label=f'{name}_{i:02}', role=role, acquisition_mode='stepped',
                          mean_u=round(.30/math.cosh(a/2), 9), depth_a=a,
                          half_period_s=half, transitions_per_polarity=n,
                          settle_s=settle, pause_before=False)
            text += '\n[[point]]\n'+'\n'.join(f'{k} = {scalar(v)}' for k,v in values.items())+'\n'
            seconds += 2*half*n+settle+.25+OVERHEAD
        return self.acquisition(name, kind, 'toml', text, len(specs), seconds)

    def static(self, name, duration):
        text = f'mode = "current_reference"\nname = "{name}"\nduration_s = {duration}\nsettle_s = 10\nrepeats = 1\n'
        return self.acquisition(name, 'A4', 'toml', text, 1, duration+10+OVERHEAD)

    def block(self, name, protocol, state, candidate=None, camera_from=None, **extra):
        entry = next(e for e in self.catalog if e['name']==protocol)
        block = dict(experiment=entry['experiment'], name=name, protocol=protocol,
                     optical_state=state, estimated_points=entry['points'],
                     estimated_seconds=entry['seconds'], retry_same_point=True,
                     required_artifacts=['raw','pdq','camera_sidecar','monitoring','protocol_receipt'])
        if camera_from: block['camera_from'] = camera_from
        if candidate is not None: block['camera'] = CANDIDATES[candidate]
        block.update(extra)
        return block

    def campaign(self, filename, program, blocks, states, limit=None, closing_seconds=900):
        values = dict(name=filename.removesuffix('.toml'), version=VERSION, program=program,
                      overhead_s_per_point=OVERHEAD)
        if limit:
            values.update(wall_clock_limit_s=limit, acquisition_cutoff_s=limit-closing_seconds)
        text = '# Generated from actual owner rows. Do not edit timing independently.\n'
        text += '\n'.join(f'{k} = {scalar(v)}' for k,v in values.items())+'\n'
        for id, target, action in states:
            text += '\n[[optical_states]]\n'+f'id = {scalar(id)}\nlabel = {scalar(id)}\ntarget_camera_lux = {scalar(target)}\noperator_action = {scalar(action)}\n'
        for block in blocks:
            text += '\n[[block]]\n'
            text += '\n'.join(f'{k} = {scalar(v)}' for k,v in block.items() if k!='camera')+'\n'
            if 'camera' in block:
                text += '[block.camera]\n'+'\n'.join(f'{k} = {scalar(v)}' for k,v in block['camera'].items())+'\n'
        self.save('stage-a-universal-runner/protocols/'+filename, text)

    def build(self):
        for name, seconds in [('static_final',90),('static_screen',45),('static_finalist',45),('static_smoke',2)]:
            self.static(name, seconds)
        self.sine('sine_smoke',[sine_row('smoke',2,.36,4,2)])
        self.steps('steps_smoke',[(.36,1,2,'smoke')])
        self.steps('load_smoke',[(.36,1,2,'smoke')], 'A5')
        self.sine('screen_response', grid([.5,8],[.08,.20,.80], 'screen',8,8)
                  + [sine_row('screen_slow_guard',.25,.80,8,8)])
        self.sine('screen_reference', [sine_row(f'reference_{a}',2,a,8,10) for a in [.20,.80]])
        self.sine('finalist_response',grid([.5,8],[.12,.80],'finalist',8,8))
        for name, fs, depths in [('main', FREQS, DEPTHS),
                                 ('lower',[.25,.5,1,2,4,8,16,32,128,512],[.04,.08,.12,.20,.36,.80])]:
            rows = grid(fs, depths, name)
            parts = [rows[:len(rows)//3],rows[len(rows)//3:2*(len(rows)//3)],rows[2*(len(rows)//3):]]
            full = []
            for i, part in enumerate(parts):
                chunk = [sine_row(f'ref_{i}_{a}',2,a) for a in [.20,.80]] + part
                if i==0: chunk = [sine_row(f'guard_{a}',.125,a) for a in [.20,.80]]+chunk
                if i==2: chunk += [sine_row(f'ref_close_{a}',2,a) for a in [.20,.80]]
                full += chunk
                self.sine(f'{name}_{i+1}',chunk)
            self.sine(f'{name}_complete',full)
        self.sine('bright_bridge',grid([2,32,256],[.20,.80],'bright'))
        self.sine('intermediate_bridge',grid([.5,4,32,256],[.20,.80],'bridge'))
        self.sine('closing_response',[sine_row(f'closing_{a}',2,a) for a in [.20,.80]])
        self.sine('slow_extension',[sine_row(f'extension_{a}',.0625,a) for a in [.20,.80]])
        self.steps('latency_core',[(a,1,25,'identification') for a in [.12,.36,.80]])
        self.steps('latency_cadence',[(.36,.5,25,'cadence'),(.36,2,25,'cadence')])
        self.steps('latency_bridge',[(a,1,50,'interpolation_check') for a in [.12,.80]])
        self.steps('heldout_temporal',[(a,h,20,'held_out_not_for_fitting') for a in [.24,.60] for h in [.35,1.5]])
        self.steps('load_recovery',[(a,h,100,'effective_rate_recovery') for a in [.36,.80] for h in [.5,.05,.005]],'A5')
        self.steps('load_roi_compare',[(.80,.005,100,'matched_roi_load')],'A5')
        states = [('DARK','laser off','Switch the laser off. Keep the optical path unchanged; confirm the laser-off reference.'),
                  ('F0','about 8','Switch the laser on. Set the AOD for about 8 camera-lux; wait for stable readback.'),
                  ('F2','about 0.08','Keep the laser on. Set the AOD for about 0.08 camera-lux; wait for stable readback.'),
                  ('F1','about 0.8','Keep the laser on. Set the AOD for about 0.8 camera-lux; wait for stable readback.'),
                  ('LOW','about 0.03','Keep the laser on. Set the AOD for about 0.03 camera-lux; wait for stable readback.'),
                  ('MID','about 0.3','Keep the laser on. Set the AOD for about 0.3 camera-lux; wait for stable readback.')]
        final=[]
        def add(name,protocol,state,**kw): final.append(self.block(name,protocol,state,camera_from='selected',**kw))
        add('laser_off_open','static_final','DARK')
        for state in ['F2','F1']:
            add(f'{state}_background_pre','static_final',state)
            for i in range(1,4): add(f'{state}_main_{i}',f'main_{i}',state)
            add(f'{state}_latency','latency_core',state)
            if state=='F2':
                add('F2_cadence','latency_cadence',state)
                add('F2_heldout','heldout_temporal',state)
            add(f'{state}_background_post','static_final',state)
        add('closing_background','static_final','F2',closing=True)
        add('closing_response','closing_response','F2',closing=True)
        add('laser_off_close','static_final','DARK',closing=True)
        self.campaign('stage-a-grand-final.toml','selected_state_final',final,
                      [s for s in states if s[0] in ['DARK','F2','F1']],10800)
        screen=[]
        for i, c in enumerate([0,4,2,3,1,5]):
            for protocol in ['static_screen','screen_response']:
                screen.append(self.block(f'F2_B{c}_{protocol}',protocol,'F2',candidate=c))
            if i in [2,5]:
                for protocol in ['static_screen','screen_reference']:
                    screen.append(self.block(f'F2_B0_repeat_{i}_{protocol}',protocol,'F2',candidate=0))
        for state in ['F1']:
            for slot in ['finalist_1','finalist_2']:
                for protocol in ['static_finalist','finalist_response']:
                    screen.append(self.block(f'{state}_{slot}_{protocol}',protocol,state,camera_from=slot))
        for block in screen[-2:]: block['closing'] = True
        self.campaign('stage-a-dim-bias-selection.toml','dim_bias_selection',screen,
                      [s for s in states if s[0] in ['F2','F1']],3000,closing_seconds=300)
        smoke=[self.block(name,p,'F2',candidate=4) for name,p in [('a1','sine_smoke'),('a2','steps_smoke'),('a3','sine_smoke'),('a4','static_smoke'),('a5','load_smoke')]]
        smoke[2]['experiment']='A3'
        self.campaign('stage-a-smoke-test.toml','smoke',smoke,[s for s in states if s[0]=='F2'])
        bright=[self.block(name,name,'F0',camera_from='selected') for name in ['bright_bridge','static_final','load_recovery']]
        self.campaign('stage-a-all.toml','bright_reference',bright,[s for s in states if s[0]=='F0'])
        self.campaign('a6_camera_lux_reference.toml','camera_lux_reference',
            [self.block('camera_lux_reference','static_final','F2',camera_from='selected')],
            [s for s in states if s[0]=='F2'])
        self.save('stage-a-universal-runner/protocols/acquisition/catalog.json',json.dumps(self.catalog,indent=2)+'\n')
        code = '// Generated by scripts/build_universal_protocols.py.\nuse super::{BuiltinProtocol, Experiment};\n\n#[rustfmt::skip]\npub const PROTOCOLS: &[BuiltinProtocol] = &[\n'
        for e in self.catalog:
            relative='../protocols/acquisition/'+e['name']+'.'+e['extension']
            code += '    BuiltinProtocol { name: '+scalar(e['name'])+', experiment: Experiment::'+e['experiment']+', extension: '+scalar(e['extension'])+', contents: include_str!('+scalar(relative)+'), points: '+str(e['points'])+', seconds: '+str(e['seconds'])+' },\n'
        self.save('stage-a-universal-runner/src/protocol_catalog.rs',code+'];\n')

    def write(self, check=False):
        changed=[]
        for name,text in self.files.items():
            path=self.root/name
            if not path.exists() or path.read_text()!=text:
                changed.append(name)
                if not check:
                    path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text)
        if check and changed: raise SystemExit('Generated files differ: '+', '.join(changed))
        print(f'{len(self.catalog)} owner protocols; {len(changed)} files '+('differ' if check else 'updated'))

if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    builder=Builder(Path(__file__).resolve().parents[1]);builder.build();builder.write(args.check)
